# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"

stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: "#82aaff"
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: "#ff966c"
